### ISSUE TITLE
Checkbox load fails due to $POST being an array

### ISSUE THREAD

**Issue by The0mikkel** [The0mikkel/WPPlugin-HTXLan#103]
On the form page, the page does not load, due to a critical error in the code, where the `explode()` on line 1405 in `functions.php` (as of this issue being opened), fails, due to `$POST` being an array. It is expected for this `$POST` to not be set. 

This may have been caused by some update.

**Comment by frej4189** [comment]
$POST should be a dictionary?

**Comment by The0mikkel** [comment]
It's just weird, this issue is present, when the user have just loaded the page, and not posted something

**Comment by The0mikkel** [comment]
I have temporarily fixed the issue by changing the `if (isset($POST)) {` to `if (isset($POST) && !is_array($POST)) {` on [line 1405](https://github.com/HTX-LAN/wp-htxlan/blob/d6b90b419d006b59deb3c34b945d1b569159a0bb/code/functions.php#L1404C29-L1404C48).  

And yes, if we make a new release, that will break. So hopefully, this issue can be resolved before any new releases.

**Comment by frej4189** [comment]
My PHP is a bit rusty, but seems to be caused by:

- isset checks whether an object is explicitly null.

- $_POST is most likely an empty array/dict when request is not a POST (i.e. not explicitly null)


Should be fixable by checking whether request method is POST instead of using isset.

**Comment by The0mikkel** [comment]
Very valid - I will see if I can find some time in the next few days to fix it.

I also seem to experience multiple PHP warnings when submitting. Maybe they can be explored a bit as well.

Time for some maintenance!

**Comment by The0mikkel** [comment]
This was solved, with an inline handling of it either being an array or string:
```php
!is_array($POST) ? explode(",", $POST) : $POST
```
